// filename: src/lib.rs
// destination: Eco-Fort/artifact_registry_core/src/lib.rs

pub struct ArtifactRecord {
    pub artifactid: i64,
    pub repoid: i64,
    pub repofileid: i64,
    pub shardid: Option<i64>,
    pub catalogid: Option<i64>,
    pub mt6883registryid: Option<i64>,
    pub repotarget: String,
    pub destinationpath: String,
    pub filename: String,
    pub fileext: String,
    pub artifactkind: String,
    pub contenthash: String,
    pub sizebytes: Option<i64>,
    pub primaryplane: String,
    pub secondaryplanes: Option<String>,
    pub lane: String,
    pub kerband: String,
    pub planecontractid: Option<i64>,
    pub blastradiusid: Option<i64>,
    pub kmetric: Option<f64>,
    pub emetric: Option<f64>,
    pub rmetric: Option<f64>,
    pub vtmax: Option<f64>,
    pub kerdeployable: bool,
    pub evidencehex: String,
    pub rohanchorhex: Option<String>,
    pub signingdid: String,
    pub provenancehex: Option<String>,
    pub createdutc: String,
    pub updatedutc: String,
    pub active: bool,
}

pub struct ProvenanceRecord {
    pub provenanceid: i64,
    pub artifactid: i64,
    pub cirunid: String,
    pub workflowfile: String,
    pub repo_slug: String,
    pub energymode: String,
    pub lane: String,
    pub kmetric: f64,
    pub emetric: f64,
    pub rmetric: f64,
    pub vtmax: f64,
    pub kerdeployable: bool,
    pub status: String,
    pub planecontractid: Option<i64>,
    pub rohanchorhex: Option<String>,
    pub lanestatusid: Option<i64>,
    pub createdutc: String,
    pub updatedutc: String,
}
