-- filename: seed_qpushardcatalog_artifactregistry.sql
-- destination: Eco-Fort/db/seed_qpushardcatalog_artifactregistry.sql

INSERT INTO qpushardcatalog (
    shardid,            -- optional, if using autoincrement use NULL here
    repotarget,
    destinationpath,
    filename,
    fileext,
    shardtitle,
    shardkind,
    primaryplane,
    region,
    timespan,
    versionlabel,
    qpulogicalid,
    hardwarefamily,
    hardwareprofile,
    vcorecount,
    vrammebibytes,
    memoryqubits,
    vfsnamespace,
    vfsopcode,
    vfsopkind,
    vfscontract,
    requiredinputs,
    emittedoutputs,
    energydomain,
    energylane,
    maintenancerole,
    costreductionscore,
    uptimeclass,
    citizenid,
    augmentationprofile,
    continuitystateref
)
VALUES (
    NULL,
    'Eco-Fort',
    'db',
    'dbartifactregistry.sql',
    'sql',
    'Eco-Fort Artifact Registry Schema 2026v1',
    'STATE',                    -- STATE, PLAN, TRACE, INDEX
    'dataquality',              -- governance/metadata plane
    'Global',
    'static',
    'ArtifactRegistrySchema2026v1',
    'QPU-ECOFORT-CATALOG-0001',
    'VIRTUAL_SQLITE',
    'EcoFortCatalogLowPower',
    1,
    256,
    0,
    'ECOFORT.DB',
    'VOP_ARTIFACT_REGISTRY',
    'METADATA',
    'ArtifactRegistryContract2026v1',
    'repo,repofile,shardinstance,planeweights,blastradiusindex,mt6883registry',
    'artifactregistry,artifactprovenance,v_artifact_*',
    'INFRA',
    'LOWPOWER',
    'CATALOG_MAINTAINER',
    0.95,
    'ALWAYS_ON',
    NULL,
    NULL,
    NULL
);
